let songs = [
  {
    name: "Janji Kasih",
    path: "Song/Tiara Andini - Janji Setia (Official Music Video).mp3",
    artist: "Tiara Andini",
    cover: "Img/Janji-kasih.jpg",
  },
  {
    name: "Denting",
    path: "Song/Denting - Petra Sihombing  Lirik Lagu.mp3",
    artist: "Petra Sihombing",
    cover: "Img/Denting.jpg",
  },
  {
    name: "Cinta Terbaik",
    path: "Song/Cassandra - Cinta Terbaik (Official Music Video).mp3",
    artist: "Cassandra",
    cover: "Img/cinta-terbaik.jpg",
  },
  {
    name: "Mengejar Mimpi",
    path: "Song/YOVIE & NUNO - Mengejar Mimpi.mp3",
    artist: "Yovie & Nuno",
    cover: "Img/Yovie-Yuno.jpeg",
  },
  {
    name: "Menjaga Hati",
    path: "Song/Yovie & Nuno - Menjaga Hati (Video Clip).mp3",
    artist: "Yovie & Nuno",
    cover: "Img/Menjaga-hati.jpg",
  },
  {
    name: "Tanpa Cinta",
    path: "Song/Yovie & Nuno - Tanpa Cinta (Video Clip).mp3",
    artist: "Yovie & Nuno",
    cover: "Img/tanpa-cinta.jpg",
  },
  {
    name: "Manusia Biasa",
    path: "Song/Yovie & Nuno - Manusia Biasa (CLB).mp3",
    artist: "Yovie & Nuno",
    cover: "Img/manusia-biasa.jpg",
  },
  {
    name: "Kenanglah Aku",
    path: "Song/Naff - Kenanglah Aku  Video Lirik.mp3",
    artist: "Naff",
    cover: "Img/kenanglah-aku.jpg",
  },
  {
    name: "Jaga Selalu Hatimu",
    path: "Song/Jaga Slalu Hatimu -Seventeen- Lirik.mp3",
    artist: "Seventeen",
    cover: "Img/jaga-selalu-hatimu.jpg",
  },
  {
    name: "Memikirkan Dia",
    path: "Song/Seventeen - Memikirkan Dia (Official Audio).mp3",
    artist: "Seventeen",
    cover: "Img/memikirkan-dia.jpg",
  },
  {
    name: "Menemukanmu",
    path: "Song/Seventeen - Menemukanmu (Official Music Video).mp3",
    artist: "Seventeen",
    cover: "Img/menemukanmu.jpg",
  },
  {
    name: "Abadi",
    path: "Song/Dendi Nata - Abadi (Indo Version) Lyric Video.mp3",
    artist: "Dendi Nata",
    cover: "Img/abadi.jpg",
  },
  {
    name: "Cinta Sejati",
    path: "Song/Bunga Citra Lestari - Cinta Sejati _Ost Habibie Ainun_ I Official Music Video.mp3",
    artist: "Bunga Citra Sejati",
    cover: "Img/cinta-sejati.jpg",
  },
  {
    name: "Kisinan",
    path: "Song/KISINAN - MASDDDHO (OFFICIAL MUSIC VIDEO).mp3",
    artist: "Masdddho",
    cover: "Img/kisinan.jpg",
  },
  {
    name: "Aku Kamu dan Samudra",
    path: "Song/Rebellion Rose -  Aku, Kamu dan Samudra (Official Music Video & murphydarchy prewedding video).mp3",
    artist: "Rebellion Rose",
    cover: "Img/aku-kamu-dan-samudra.jpg",
  },
  {
    name: "Menepi",
    path: "Song/MENEPI - NGATMOMBILUNG  GUYONWATON COVER.mp3",
    artist: "Guyon Waton",
    cover: "Img/menepi.jpg",
  },
];
